### ISSUE TITLE
OSGi import-package strategy for classes available in java core but not necessarily in the platform

### ISSUE THREAD

**Issue by jandernascimento** [AdeleResearchGroup/ApAM#76]
> Description

Bundles requires to explicitly declare import-package for classes even if they are used by apam framework for somereason. An example is: an exception declared in the dependency tag should not be imported by the bundle that should receive this dependency, since it is apam itself that throws the exception, but in fact its mandatory for the bundle to declare import-package in order to be able to load and throw the exception declared.

In order to bypass this problem temporarily, the test ``fr.imag.adele.apam.test.testcases.DynamanDependentTest.CompositeDependencyFailExceptionNative_tc052()`` we added an import of the exception raised by apam (javax.xml.ParserConfigurationException) in the bundle containing the class for the implementation declared in apam.

>  How to reproduce

* Remove the declaration ``ParserConfigurationException e;`` from the class ``S3GroupAImpl``
* launch the test ``fr.imag.adele.apam.test.testcases.DynamanDependentTest.CompositeDependencyFailExceptionNative_tc052()``

>  Expected outcome

The same expected by the test case.

**Comment by gevegab** [comment]
This issue is in fact not related to APAM. It is related on how to use java core classes in OSGi. Usually for classes in the packages java.* there is nothing to do. 

For classes in the javax.* packages there is no special treatment and they must be explicitly imported (like any other class) by the client bundle. 

The only alternative to avoid explicit exports is to use the property
 org.osgi.framework.bootdelegation 
when launching the framework to specify the packages that must be imported implicitly.

This is solution shown in test fr.imag.adele.apam.test.testcases.FailureTest, see the method config() for initialization of the property


See http://spring.io/blog/2009/01/19/exposing-the-boot-classpath-in-osgi/ for a description of the problem and possible solutions
